server:
  port: 1113

spring:
  application:
    name: member-service
    jpa:
      generate-ddl: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      url: jdbc:mysql://localhost:3306/library?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&tinyInt1isBit=false&createDatabaseIfNotExist=true&useSSL=false
      password: Decipher@123


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    hostname: localhost


#RESTCLINET_USER_URL: lo