version: '3.3'
services:
  library-db:
    image: mysql:latest
#    build: .
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Decipher@123'
      MYSQL_USER: 'root'
      MYSQL_DATABASE: 'library'
    ports:
      - '3308:3306'
    networks:
      - library-network

  book-service:
    build: ./user-limit-service/
#      dockerfile: book-service/Dockerfile
    ports:
      - "1114:1114"
    expose:
      - 1114
    networks:
      - library-network
    depends_on:
      - library-db
    links:
      - library-db
 #   environment:
 #     - DATABASE_USER=root
 #     - DATABASE_PASSWORD=root
 #     - DATABASE_NAME=library

