version: "3"
services:
  library_db:
    image: library_db
    ports:
      - "1112:1112"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8

    environment:
      - MYSQL_ROOT_PASSWORD=Decipher@123
      - MYSQL_DATABASE=library
